version: "2"
services:
  nodejs:
    image: quiz-server
    user: node
    working_dir: /usr/src/app
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - 80:8000
    depends_on:
      - "mongodb"
  mongodb:
    image: mongo:latest
    expose:
      - "27017"
    command: "--storageEngine wiredTiger"